// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_apiBD_comprobarlogin from "./routes/(apiBD)/comprobarlogin.ts";
import * as $_apiBD_comprobarregistro from "./routes/(apiBD)/comprobarregistro.ts";
import * as $_apiBD_nuevofavorito from "./routes/(apiBD)/nuevofavorito.ts";
import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_platform_characters from "./routes/(platform)/characters.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $register from "./routes/register.tsx";
import * as $IslaCharacter from "./islands/IslaCharacter.tsx";
import * as $IslaLogin from "./islands/IslaLogin.tsx";
import * as $islaRegister from "./islands/islaRegister.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(apiBD)/comprobarlogin.ts": $_apiBD_comprobarlogin,
    "./routes/(apiBD)/comprobarregistro.ts": $_apiBD_comprobarregistro,
    "./routes/(apiBD)/nuevofavorito.ts": $_apiBD_nuevofavorito,
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/(platform)/characters.tsx": $_platform_characters,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/register.tsx": $register,
  },
  islands: {
    "./islands/IslaCharacter.tsx": $IslaCharacter,
    "./islands/IslaLogin.tsx": $IslaLogin,
    "./islands/islaRegister.tsx": $islaRegister,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
